input {
	beats {
		port => 5044
	}
	tcp {
		port => 6000
		codec => json
	}
}

filter {
    mutate { 
        gsub => ["message", "@($NL$)@", "\r\n"]
        replace => { "[@metadata][beat]" => "atmosphere-engine-logs" }
    }
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		ecs_compatibility => disabled
		index => "atmosphere-engine-logs"
	}
}