<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <DefineConstants>$(DefineConstants);$(ACoreEnvironment);$(ACoreBuild)</DefineConstants>
        <AssemblyName>Fb.Mechanics.Module</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AGame.Actors\AGame.Actors.csproj" />
      <ProjectReference Include="..\AGame.Core\AGame.Core.csproj" />
      <ProjectReference Include="..\AGame.Transform\AGame.Transform.csproj" />
      <ProjectReference Include="..\AUtils.IoC\AUtils.IoC.csproj" />
    </ItemGroup>

</Project>
