using System.ComponentModel;
using System.Reflection;
using System.Text;

namespace AUtils.Sil.Compiler;

internal static class StringBuilderExtension
{
    public static void AppendAutogen(this StringBuilder builder)
    {
        builder.AppendLine($"// Autogenerated by Sil Compiler. Don't modify. {DateTime.Now:O}");
        builder.AppendLine();
    }
    
    public static void AppendDescription(this StringBuilder builder, Type type, int tab = 0)
    {
        if (type == null) 
            throw new ArgumentNullException(nameof(type));
        
        if (builder == null) 
            throw new ArgumentNullException(nameof(builder));

        var description = type.GetCustomAttribute<DisplayNameAttribute>()?.DisplayName;
        if (string.IsNullOrEmpty(description)) 
            return;

        var spaces = new char[tab * 4];
        Array.Fill(spaces, ' ');
        var tabString = new string(spaces);
        
        builder.AppendLine($"{tabString}/**");
        builder.AppendLine($"{tabString} * @brief {description}");
        builder.AppendLine($"{tabString} */");
    }
}