<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <DefineConstants>$(DefineConstants);$(ACoreEnvironment);$(ACoreBuild)</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="ACore.Abstractions.csproj.DotSettings" />
    </ItemGroup>

</Project>
