<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <DefineConstants>$(DefineConstants);$(ACoreEnvironment);$(ACoreBuild)</DefineConstants>
        <AssemblyName>ACore.Minio.Module</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ACore.Abstractions\ACore.Abstractions.csproj" />
      <ProjectReference Include="..\AUtils.IoC\AUtils.IoC.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Minio" Version="4.0.7" />
    </ItemGroup>

</Project>
